CREATE TYPE "user_role" AS ENUM (
  'user',
  'admin'
);

CREATE TYPE "user_status" AS ENUM (
  'inactive',
  'active',
  'banned',
  'overlimitstorage'
);

CREATE TYPE "document_visibility" AS ENUM (
  'private',
  'public'
);

CREATE TYPE "document_status" AS ENUM (
  'uploading',
  'processing',
  'pending',
  'rejected',
  'deleted',
  'failed',
  'completed'
);

CREATE TYPE "invoice_status" AS ENUM (
  'pending',
  'success',
  'failed'
);

CREATE TYPE "message_sender" AS ENUM (
  'user',
  'bot'
);

CREATE TYPE "report_status" AS ENUM (
  'pending',
  'resolved',
  'rejected'
);

CREATE TABLE "storage_plans" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "storage_limit" bigint NOT NULL,
  "max_ai_requests_per_day" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255),
  "full_name" varchar(100),
  "avatar_url" varchar(255),
  "role" user_role DEFAULT 'user',
  "status" user_status DEFAULT 'active',
  "plan_id" integer DEFAULT 1,
  "storage_used" bigint DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "google_id" varchar(255) UNIQUE,
  "plan_expires_at" timestamp,
  "is_storage_counted" boolean DEFAULT true
);

CREATE TABLE "invoices" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "plan_id" integer,
  "amount" decimal(10,2) NOT NULL,
  "provider" varchar(50),
  "transaction_id" varchar(100) UNIQUE,
  "status" invoice_status DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "duration_days" integer DEFAULT 30
);

CREATE TABLE "documents" (
  "id" uuid PRIMARY KEY,
  "uploader_id" uuid,
  "title" varchar(255) NOT NULL,
  "file_url" varchar(255) NOT NULL,
  "file_type" varchar(20),
  "file_size_bytes" bigint NOT NULL,
  "status" document_status DEFAULT 'uploading',
  "visibility" document_visibility DEFAULT 'private',
  "link_share" varchar(255) UNIQUE,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp,
  "rejection_reason" text
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "document_tags" (
  "document_id" uuid,
  "tag_id" integer,
  PRIMARY KEY ("document_id", "tag_id")
);

CREATE TABLE "chat_sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "title" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "session_documents" (
  "session_id" uuid,
  "document_id" uuid,
  PRIMARY KEY ("session_id", "document_id")
);

CREATE TABLE "chat_messages" (
  "id" uuid PRIMARY KEY,
  "session_id" uuid,
  "sender" message_sender NOT NULL,
  "content" text NOT NULL,
  "citations" jsonb,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "reviews" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "document_id" uuid,
  "rating" integer NOT NULL,
  "comment" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "reports" (
  "id" uuid PRIMARY KEY,
  "reporter_id" uuid,
  "document_id" uuid,
  "reason" text NOT NULL,
  "status" report_status DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "violation_histories" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "reason" text NOT NULL,
  "status" varchar(50),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE "document_chunks" (
  "id" uuid PRIMARY KEY,
  "document_id" uuid,
  "chunk_index" integer NOT NULL,
  "content" text NOT NULL,
  "embedding" vector(1536),
  "metadata" jsonb,
  "page_number" integer,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS visibility document_visibility DEFAULT 'private';

ALTER TABLE "document_chunks" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON DELETE CASCADE;

CREATE INDEX document_chunks_embedding_hnsw_idx ON document_chunks USING hnsw (embedding vector_cosine_ops);

ALTER TABLE "users" ADD COLUMN "bio" TEXT;

ALTER TABLE "documents" ADD COLUMN "summary" TEXT;

ALTER TABLE "documents" ADD COLUMN "description" TEXT;

ALTER TABLE "users" ADD FOREIGN KEY ("plan_id") REFERENCES "storage_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("plan_id") REFERENCES "storage_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("uploader_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session_documents" ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session_documents" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "violation_histories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
